name: Python Django CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        django-version: ['3.0', '3.1', '3.2', '4.0', '4.1', '4.2']
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip
      run: python -m pip install --upgrade pip

    - name: Install tox
      run: pip install tox tox-gh-actions

    - name: Run tox
      run: tox

    - name: Run Doctests
      run: |
        tox -e doctests

    - name: Run Flake8 Tests
      run: |
        tox -e flake8
